FROM registry.suse.com/bci/openjdk-devel:21

WORKDIR /app

# Copy Maven wrapper and pom.xml
COPY mvnw .
COPY mvnw.cmd .
COPY .mvn .mvn
COPY pom.xml .

# Download dependencies
RUN ./mvnw dependency:go-offline -B

# Copy source code
COPY src ./src

# Build application
RUN ./mvnw clean package -DskipTests

# Expose port
EXPOSE 8080

# Run application with development profile
ENTRYPOINT ["java", "-jar", "target/videos-api-0.0.1-SNAPSHOT.jar"]
