spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/techchallenge
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/techchallenge
    user: postgres
    password: postgres
client:
  pagamento:
    base-url: "http://localhost:8080/pagamentos"