spring:
  datasource:
    url: jdbc:postgresql://localhost-prod:5432/techchallenge
    username: "root"
    password: "m@_ssq@HJ7<h(+"
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost-prod:5432/techchallenge
    user: "root"
    password: "m@_ssq@HJ7<h(+"


azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=https;AccountName=your-account;AccountKey=your-key;EndpointSuffix=core.windows.net}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:videos}

topics:
  video-upload: ${KAFKA_TOPIC_VIDEO_UPLOAD:video.uploaded}
  video-status-update: ${KAFKA_TOPIC_VIDEO_STATUS_UPDATE:video.status}