spring:
  datasource:
    url: jdbc:postgresql://localhost-prod:5432/techchallenge
    username: "root"
    password: "m@_ssq@HJ7<h(+"
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost-prod:5432/techchallenge
    user: "root"
    password: "m@_ssq@HJ7<h(+"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:video-api-consumer-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      connect-timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=https;AccountName=your-account;AccountKey=your-key;EndpointSuffix=core.windows.net}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:videos}

kafka:
  topics:
    video-upload: ${KAFKA_TOPIC_VIDEO_UPLOAD:video-upload-events}
    video-status-update: ${KAFKA_TOPIC_VIDEO_STATUS_UPDATE:video-status-update-events}