spring:
  datasource:
    url: jdbc:postgresql://localhost-prod:5432/techchallenge
    username: "root"
    password: "m@_ssq@HJ7<h(+"
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost-prod:5432/techchallenge
    user: postgres
    password: postgres
client:
  pagamento:
    base-url: "http://java-app-pagamento/pagamentos"