spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/techchallenge
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/techchallenge
    user: "postgres"
    password: "postgres"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:video-api-consumer-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1

# Mock services configuration
azure:
  storage:
    mock:
      enabled: true
    connection-string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;
    container-name: videos

kafka:
  mock:
    enabled: true
  topics:
    video-upload: ${KAFKA_TOPIC_VIDEO_UPLOAD:video-upload-events}
    video-status-update: ${KAFKA_TOPIC_VIDEO_STATUS_UPDATE:video-status-update-events}

# Logging configuration for development
logging:
  level:
    br.com.fiap.videosapi: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    org.apache.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
