spring:
  profiles:
    active: local
  application:
    name: videos-api
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG}
      ssl.endpoint.identification.algorithm: https
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:video-api-consumer-group}
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: alpha
    docExpansion: none

tag:
  swagger:
    video:
      name: "Video Management"
      description: "API for video upload and management"

server:
  servlet:
    context-path: /videos