apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: service-account-hpa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa-role
  namespace: default
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-metrics-access
  namespace: default
subjects:
  - kind: ServiceAccount
    name: service-account-hpa
    namespace: default
roleRef:
  kind: Role
  name: hpa-role
  apiGroup: rbac.authorization.k8s.io

