apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  POSTGRES_USER: "adminfiap"
  POSTGRES_PASSWORD: "m@_ssq@HJ7<h(+"
  POSTGRES_DB: "techchallenge"
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=<your_account_name>;AccountKey=<your_account_key>;EndpointSuffix=core.windows.net"